作業目標<br>
熟悉陣列維度轉換，並且會擷取需要資料<br>
作業重點<br>
使用reshap須注意order用法<br>
where可以運用邏輯條件擷取資料

In [2]:
import numpy as np

In [10]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
array2 = array1.reshape(5, 6, order = 'F')
print(array2)

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [13]:
#2.呈上題的array，找出被6除餘1的數的索引
array3 = []
for i in range(0, array2.shape[0]):
    for j in range(0, array2.shape[1]):
        if array2[i][j] % 6 == 1:
            array3.append(array2[i][j])
print(array3)

[25, 1, 7, 13, 19]
