# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [1]:
import numpy as np
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [2]:
%timeit -n 10 a = 2
Z + 1

22.9 ns ± 7 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


array([[[ 1,  9,  3, ...,  1,  4,  7],
        [ 9,  1,  3, ...,  5,  1,  8],
        [ 6, 10,  7, ...,  1,  3,  5],
        ...,
        [ 8,  6,  3, ...,  3,  2,  8],
        [ 6,  5,  7, ...,  3,  7,  1],
        [ 9,  4,  7, ...,  8,  1,  7]],

       [[ 9,  7,  7, ...,  1,  7,  8],
        [ 5,  8, 10, ...,  1,  9, 10],
        [ 9, 10, 10, ...,  8, 10,  1],
        ...,
        [ 8,  3,  1, ..., 10,  1,  8],
        [ 3,  3,  7, ...,  1,  9,  3],
        [ 3,  8,  2, ...,  2,  7,  1]],

       [[ 6,  4,  2, ...,  1,  6, 10],
        [ 4,  1,  2, ...,  8,  6,  6],
        [10,  9,  5, ...,  8,  5,  1],
        ...,
        [ 5,  1,  8, ...,  6,  1,  4],
        [ 6,  6,  8, ...,  1,  9,  3],
        [ 9, 10,  4, ...,  3,  1,  5]],

       ...,

       [[ 3,  7,  7, ...,  9,  3,  9],
        [ 1,  3,  5, ...,  4,  6,  6],
        [ 9,  6,  2, ...,  8,  4,  3],
        ...,
        [ 3,  7, 10, ...,  6,  6,  3],
        [ 4,  2,  8, ...,  4,  3, 10],
        [ 9,  7,  6, ...,  4,  8

In [3]:
%timeit -n 10 a = 2
Z_flat = []
for i in Z.flatten():
    Z_flat.append(i+1)
Z1 = np.array(Z_flat).reshape(100, 100, 100)

20 ns ± 9.26 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
%timeit -n 10 a = 2
Z2 = np.array([i+1 for i in Z.flatten()]).reshape(100, 100, 100)
print(Z2)

18.6 ns ± 9.9 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
[[[ 1  9  3 ...  1  4  7]
  [ 9  1  3 ...  5  1  8]
  [ 6 10  7 ...  1  3  5]
  ...
  [ 8  6  3 ...  3  2  8]
  [ 6  5  7 ...  3  7  1]
  [ 9  4  7 ...  8  1  7]]

 [[ 9  7  7 ...  1  7  8]
  [ 5  8 10 ...  1  9 10]
  [ 9 10 10 ...  8 10  1]
  ...
  [ 8  3  1 ... 10  1  8]
  [ 3  3  7 ...  1  9  3]
  [ 3  8  2 ...  2  7  1]]

 [[ 6  4  2 ...  1  6 10]
  [ 4  1  2 ...  8  6  6]
  [10  9  5 ...  8  5  1]
  ...
  [ 5  1  8 ...  6  1  4]
  [ 6  6  8 ...  1  9  3]
  [ 9 10  4 ...  3  1  5]]

 ...

 [[ 3  7  7 ...  9  3  9]
  [ 1  3  5 ...  4  6  6]
  [ 9  6  2 ...  8  4  3]
  ...
  [ 3  7 10 ...  6  6  3]
  [ 4  2  8 ...  4  3 10]
  [ 9  7  6 ...  4  8 10]]

 [[ 2  1  2 ...  1  4  3]
  [10  3  1 ...  6  6  4]
  [ 1  7  4 ...  3  5  4]
  ...
  [ 3  3  9 ...  1  8  9]
  [ 1  6 10 ...  9  5 10]
  [ 9  3 10 ...  2  5  6]]

 [[ 7  7  4 ...  4  2  9]
  [ 2  7  3 ...  9  2  1]
  [ 2  9  8 ...  5 10  8]
  ...
  [ 2  5  4 ...  1  

### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [7]:
np.random.seed(0)
Z = np.random.randint(0,10,50)
print(Z)

[5 0 3 3 7 9 3 5 2 4 7 6 8 8 1 6 7 7 8 1 5 9 8 9 4 3 0 3 5 0 2 3 8 1 3 3 3
 7 0 1 9 9 0 4 7 3 2 7 2 0]


In [8]:
unique, counts = np.unique(Z, return_counts = True)
Z_dict = dict(zip(unique, counts))
Z_dict

{0: 6, 1: 4, 2: 4, 3: 10, 4: 3, 5: 4, 6: 2, 7: 7, 8: 5, 9: 5}

In [9]:
Z_dict_max = max(Z_dict, key = Z_dict.get)
Z_dict_max

3

In [10]:
np.where(Z == Z_dict_max)

(array([ 2,  3,  6, 25, 27, 31, 34, 35, 36, 45], dtype=int64),)

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [17]:
np.random.seed(1)
a = np.random.randint(10, size=6) 
print(a.tolist())
print(list(a))

[5, 8, 9, 5, 0, 0]
[5, 8, 9, 5, 0, 0]


In [18]:
np.random.seed(2)
b = np.random.randint(10, size=(3,4)) 
print(b.tolist())
print(list(b))
newlist_b = []
for i in b:
    newlist_b.append(list(i))
print(newlist_b)

[[8, 8, 6, 2], [8, 7, 2, 1], [5, 4, 4, 5]]
[array([8, 8, 6, 2]), array([8, 7, 2, 1]), array([5, 4, 4, 5])]
[[8, 8, 6, 2], [8, 7, 2, 1], [5, 4, 4, 5]]


In [33]:
np.random.seed(3)
c = np.random.randint(10, size=(2,3,2)) 
print(c.tolist())
print(list(c))
newlist_c = []
for i in range(c.shape[0]):
    for j in range(c.shape[1]):
        print(c[i][j])

[[[8, 9], [3, 8], [8, 0]], [[5, 3], [9, 9], [5, 7]]]
[array([[8, 9],
       [3, 8],
       [8, 0]]), array([[5, 3],
       [9, 9],
       [5, 7]])]
[8 9]
[3 8]
[8 0]
[5 3]
[9 9]
[5 7]


In [48]:
np.random.seed(3)
c = np.random.randint(10, size=(2,3,2)) 
print(c.tolist())
print(list(c))
newlist_c = []
for i in range(c.shape[0]):
    for j in range(c.shape[1]):
        newlist_c.append(list(c[i][j]))
print(newlist_c)

[[[8, 9], [3, 8], [8, 0]], [[5, 3], [9, 9], [5, 7]]]
[array([[8, 9],
       [3, 8],
       [8, 0]]), array([[5, 3],
       [9, 9],
       [5, 7]])]
[[8, 9], [3, 8], [8, 0], [5, 3], [9, 9], [5, 7]]
