### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [ ]:
'''
Your Code
np.zeros()：建立一個元素全為0的陣列。
np.empty():建立一個全新未初始化之陣列。
'''

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [28]:
import numpy as np
a = np.random.rand(2, 3)
print((a * 100).round())

[[19. 54. 50.]
 [86. 21. 28.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [70]:
m = 20
n = 40
a = np.random.rand(2, 3)
a = (a * 100).round()
b = a.reshape(-1)
num = 0
for i in b:
    if i < 20:
        b[num] = np.random.randint(20, high = 40)
    if i > 40:
        b[num] = np.random.randint(20, high = 40)
    num += 1
c = b.reshape(a.shape)
print(c)

[[25. 39. 35.]
 [24. 26. 25.]]
