In [ ]:
題目:
1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
2.呈上題，將以上數列取出偶數。
3.呈1題，將數列取出3的倍數。

In [3]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
import numpy as np
array = np.arange(0, 21, 1)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [22]:
#2.呈上題，將以上數列取出偶數。
array_even = []
for i in array:
    if i % 2 == 0:
        array_even.append(i)
array_even = np.array(array_even)
array_even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [21]:
#3.呈1題，將數列取出3的倍數。
array_3 = []
for j in array:
    if j % 3 == 0:
        array_3.append(j)
array_3 = np.array(array_3)
array_3

array([ 0,  3,  6,  9, 12, 15, 18])

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [ ]:
'''
Your Code
list() -> 將最外層轉換為list內層仍為array
tolist() -> 將整個array轉換成list
'''

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [ ]:
# 記得先 Import 正確的套件
import numpy as np
import random
'''
Your Code
'''

In [ ]:

a = np.random.randint(10, size=6)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))
'''
Your Code
a.ndim -> 一維陣列
a.shape -> 一維大小為6
a.size -> 陣列當中有6個元素
a.dtype -> 資料型態為int32
a.itemsize -> 陣列中元素占多少位元組(32 / 8 = 4)
len(a) -> 陣列長度為6
type(a) -> a為numpy.ndarray
'''

In [ ]:
b = np.random.randint(10, size=(3,4)) 
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))
'''
Your Code
b.ndim -> 二維陣列
b.shape -> 一維大小為3；二為大小為4
b.size -> 陣列當中有12個元素
b.dtype -> 資料型態為int32
b.itemsize -> 陣列中元素占多少位元組(32 / 8 = 4)
len(b) -> 陣列長度為3
type(b) -> b為numpy.ndarray
'''

In [ ]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))
'''
Your Code
c.ndim -> 三維陣列
c.shape -> 一維大小為2；二為大小為3；三為大小為2
c.size -> 陣列當中有12個元素
c.dtype -> 資料型態為int32
c.itemsize -> 陣列中元素占多少位元組(32 / 8 = 4)
len(c) -> 陣列長度為2
type(c) -> c為numpy.ndarray
'''

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [38]:
import numpy as np
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2))

In [39]:
def mytolist(array):
    newlist = []
    if array.ndim == 3:
        for x in range(0,array.shape[0]):
            for y in range(0,array.shape[1]):
                newlist.append(list(c[x][y]))
        return newlist
    if array.ndim == 2:
        for x in range(0,array.shape[0]):
            newlist.append(list(array[x]))
        return newlist
    else:
        return list(array)

In [40]:
print(mytolist(a))
print(mytolist(b))
print(mytolist(c))

[3, 7, 9, 5, 8, 4]
[[4, 0, 8, 5], [0, 7, 8, 6], [6, 7, 5, 1]]
[[6, 0], [7, 6], [5, 2], [9, 1], [1, 9], [8, 4]]
